import { defineConfig } from "oxlint";
import antiSlop from "ultracite/oxlint/anti-slop";
import core from "ultracite/oxlint/core";
import { jsPluginSettings, selectJsPlugins } from "ultracite/oxlint/js-plugins";
import next from "ultracite/oxlint/next";
import nextJsPlugins from "ultracite/oxlint/next/js-plugins";
import react from "ultracite/oxlint/react";

const jsPlugins = selectJsPlugins(["github", "sonarjs", "react-doctor"]);

export default defineConfig({
  extends: [core, react, next, nextJsPlugins, antiSlop, jsPlugins],
  // components/ui and hooks are generated by the coss/shadcn CLI and get
  // overwritten on `shadcn add`, so they follow upstream style, not ours.
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    "components/ui/**",
    "hooks/**",
  ],
  jsPlugins: jsPlugins.jsPlugins,
  settings: jsPluginSettings,
});
